//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RunAsRegistry.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RunAsRegistry.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        internal static string ButtonAbort {
            get {
                return ResourceManager.GetString("ButtonAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string ButtonAll {
            get {
                return ResourceManager.GetString("ButtonAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clos&amp;e.
        /// </summary>
        internal static string ButtonClose {
            get {
                return ResourceManager.GetString("ButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ButtonDelete {
            get {
                return ResourceManager.GetString("ButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore.
        /// </summary>
        internal static string ButtonIgnore {
            get {
                return ResourceManager.GetString("ButtonIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string ButtonNo {
            get {
                return ResourceManager.GetString("ButtonNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No To All.
        /// </summary>
        internal static string ButtonNoAll {
            get {
                return ResourceManager.GetString("ButtonNoAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ButtonOK {
            get {
                return ResourceManager.GetString("ButtonOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        internal static string ButtonRetry {
            get {
                return ResourceManager.GetString("ButtonRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        internal static string ButtonSkip {
            get {
                return ResourceManager.GetString("ButtonSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string ButtonYes {
            get {
                return ResourceManager.GetString("ButtonYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes To All.
        /// </summary>
        internal static string ButtonYesAll {
            get {
                return ResourceManager.GetString("ButtonYesAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string CaptionAbout {
            get {
                return ResourceManager.GetString("CaptionAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAPS.
        /// </summary>
        internal static string CaptionCapsLock {
            get {
                return ResourceManager.GetString("CaptionCapsLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string CaptionError {
            get {
                return ResourceManager.GetString("CaptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string CaptionHelp {
            get {
                return ResourceManager.GetString("CaptionHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string CaptionInformation {
            get {
                return ResourceManager.GetString("CaptionInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INS.
        /// </summary>
        internal static string CaptionInsert {
            get {
                return ResourceManager.GetString("CaptionInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NUM.
        /// </summary>
        internal static string CaptionNumLock {
            get {
                return ResourceManager.GetString("CaptionNumLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OVR.
        /// </summary>
        internal static string CaptionOverWrite {
            get {
                return ResourceManager.GetString("CaptionOverWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCRL.
        /// </summary>
        internal static string CaptionScrollLock {
            get {
                return ResourceManager.GetString("CaptionScrollLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string CaptionWarning {
            get {
                return ResourceManager.GetString("CaptionWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imports registry file into the system registry and launches the executable..
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple entry of arguments for the target application..
        /// </summary>
        internal static string ExceptionMessageA {
            get {
                return ResourceManager.GetString("ExceptionMessageA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple target application file path entry..
        /// </summary>
        internal static string ExceptionMessageI {
            get {
                return ResourceManager.GetString("ExceptionMessageI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arguments mismatch..
        /// </summary>
        internal static string ExceptionMessageM {
            get {
                return ResourceManager.GetString("ExceptionMessageM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple registry file path entry..
        /// </summary>
        internal static string ExceptionMessageR {
            get {
                return ResourceManager.GetString("ExceptionMessageR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown switch was provided..
        /// </summary>
        internal static string ExceptionMessageU {
            get {
                return ResourceManager.GetString("ExceptionMessageU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple working folder path entry..
        /// </summary>
        internal static string ExceptionMessageW {
            get {
                return ResourceManager.GetString("ExceptionMessageW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /i\tPath to the target application..
        /// </summary>
        internal static string HelpLine1 {
            get {
                return ResourceManager.GetString("HelpLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /T\tArgument parsing test..
        /// </summary>
        internal static string HelpLine10 {
            get {
                return ResourceManager.GetString("HelpLine10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /h or /?\tWill show this help..
        /// </summary>
        internal static string HelpLine11 {
            get {
                return ResourceManager.GetString("HelpLine11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /a\tArguments passed to the target applica-.
        /// </summary>
        internal static string HelpLine2 {
            get {
                return ResourceManager.GetString("HelpLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \ttion (optional)..
        /// </summary>
        internal static string HelpLine3 {
            get {
                return ResourceManager.GetString("HelpLine3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /w\tWorking folder of the target application.
        /// </summary>
        internal static string HelpLine4 {
            get {
                return ResourceManager.GetString("HelpLine4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \t(optional)..
        /// </summary>
        internal static string HelpLine5 {
            get {
                return ResourceManager.GetString("HelpLine5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /o\tAllow only one instance (optional)..
        /// </summary>
        internal static string HelpLine6 {
            get {
                return ResourceManager.GetString("HelpLine6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /r\tRegistry file to import into the system.
        /// </summary>
        internal static string HelpLine7 {
            get {
                return ResourceManager.GetString("HelpLine7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \tregistry before the target application is.
        /// </summary>
        internal static string HelpLine8 {
            get {
                return ResourceManager.GetString("HelpLine8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \tlaunched..
        /// </summary>
        internal static string HelpLine9 {
            get {
                return ResourceManager.GetString("HelpLine9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Icon {
            get {
                object obj = ResourceManager.GetObject("Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target framework:.
        /// </summary>
        internal static string LabelTargetFramework {
            get {
                return ResourceManager.GetString("LabelTargetFramework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        internal static string LabelVersion {
            get {
                return ResourceManager.GetString("LabelVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website:.
        /// </summary>
        internal static string LabelWebsite {
            get {
                return ResourceManager.GetString("LabelWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Copy.
        /// </summary>
        internal static string MenuItemCopy {
            get {
                return ResourceManager.GetString("MenuItemCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy &amp;About Text.
        /// </summary>
        internal static string MenuItemCopyAbout {
            get {
                return ResourceManager.GetString("MenuItemCopyAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Copy Link.
        /// </summary>
        internal static string MenuItemCopyLink {
            get {
                return ResourceManager.GetString("MenuItemCopyLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Copy URL.
        /// </summary>
        internal static string MenuItemCopyUrl {
            get {
                return ResourceManager.GetString("MenuItemCopyUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open in Default Browser....
        /// </summary>
        internal static string MenuItemOpenInDefaultBrowser {
            get {
                return ResourceManager.GetString("MenuItemOpenInDefaultBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This applicacion cannot run on your system..
        /// </summary>
        internal static string MessageApplicationCannotRun {
            get {
                return ResourceManager.GetString("MessageApplicationCannotRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has occured. Application will close now..
        /// </summary>
        internal static string MessageApplicationError {
            get {
                return ResourceManager.GetString("MessageApplicationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application to launch was not found..
        /// </summary>
        internal static string MessageApplicationNotFound {
            get {
                return ResourceManager.GetString("MessageApplicationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application to launch must be set..
        /// </summary>
        internal static string MessageApplicationNotSet {
            get {
                return ResourceManager.GetString("MessageApplicationNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry file to import was not found..
        /// </summary>
        internal static string MessageRegFileNotFound {
            get {
                return ResourceManager.GetString("MessageRegFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry file to import must be set..
        /// </summary>
        internal static string MessageRegFileNotSet {
            get {
                return ResourceManager.GetString("MessageRegFileNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The shortcut of this name already exists. Do you want to overwrite it?.
        /// </summary>
        internal static string MessageShortcutAlreadyExists {
            get {
                return ResourceManager.GetString("MessageShortcutAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application shortcut name must be set..
        /// </summary>
        internal static string MessageShortcutNameNotSet {
            get {
                return ResourceManager.GetString("MessageShortcutNameNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon OK {
            get {
                object obj = ResourceManager.GetObject("OK", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ShieldError {
            get {
                object obj = ResourceManager.GetObject("ShieldError", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ShieldOK {
            get {
                object obj = ResourceManager.GetObject("ShieldOK", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ShieldQuestion {
            get {
                object obj = ResourceManager.GetObject("ShieldQuestion", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ShieldQuestionRed {
            get {
                object obj = ResourceManager.GetObject("ShieldQuestionRed", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ShieldWarning {
            get {
                object obj = ResourceManager.GetObject("ShieldWarning", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit website.
        /// </summary>
        internal static string ToolTipVisit {
            get {
                return ResourceManager.GetString("ToolTipVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://fortsoft.eu/.
        /// </summary>
        internal static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
    }
}
